[package]
name = "readyset-client"
version = "0.1.0"
publish = false
authors = ["ReadySet Technology, Inc. <info@readyset.io>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
readyset = { path = "../readyset/readyset/" }
readyset-errors = { path = "../readyset/errors/" }
readyset-data = { path = "../readyset/data" }
timestamp_service = {path= "../readyset/timestamp_service/"}
dataflow_expression = { path = "../readyset/server/dataflow/expression" }
readyset-tracing = { path = "../readyset-tracing" }
futures-executor = "0.3.14"
futures-util = "0.3.14"
lazy_static = "1.0.0"
nom-sql = { path = "../nom-sql" }
nom = "7.1"
regex = "1.0.0"
tokio = { version = "1.15", features = ["signal", "rt-multi-thread", "time"] }
chrono = "0.4"
tracing = { version = "0.1", features = ["release_max_level_debug"] }
tracing-futures = "0.2.5"
vec1 = "1.6.0"
itertools = "0.10"
derive_more = "0.99.11"
async-trait = "0.1.49"
thiserror = "1.0.26"
launchpad = { path = "../launchpad" }
metrics = "0.19"
metrics-exporter-prometheus = "0.10"
futures = "0.3"
maplit = "1.0.2"
serde = "1.0.130"
serde_json = "1.0.67"
rust_decimal = { version = "1.16" }
bit-vec = { version = "0.6", features = ["serde"] }
hyper = { version = "0.14.10", features = [ "stream", "server" ] }
stream-cancel = "0.8.0"
tokio-stream = { version = "0.1.5", features = [ "net" ] }
tokio-tower = "0.5.1"
tower = { version = "0.4.6", features = ["util"] }
time = { version = "0.3", features = ["local-offset"] }
dashmap = "4.0.2"
mysql_common = "0.28"
bincode = "1.3.3"

readyset-server = { path = "../readyset/server" }
readyset-client-metrics = { path = "./metrics"}

[lib]
path = "src/lib.rs"

[features]
ryw = []
schema-check = []
