[package]
name = "partial_map"
version = "0.1.0"
publish = false
authors = ["ReadySet Technology, Inc. <info@readyset.io>"]
edition = "2021"

[dependencies]
unbounded-interval-tree = { path = "../../../../unbounded-interval-tree" }
